delete sync tables after sourcing the db

diff --git a/modules/openmrs/templates/restoreOpenMRS-db.sh.erb b/modules/openmrs/templates/restoreOpenMRS-db.sh.erb
--- a/modules/openmrs/templates/restoreOpenMRS-db.sh.erb
+++ b/modules/openmrs/templates/restoreOpenMRS-db.sh.erb
@@ -9,6 +9,8 @@ LOCAL_OPENMRS_DB_PASSWORD=<%= @mysql_root_password %>
 OPENMRS_DB=<%= @openmrs_db %>
 DROP_AND_CREATE_DB_SCRIPT=<%= @openmrs_create_db_sql %>
 OPENMRS_DUMP_SQL=<%= @openmrs_dump_sql %>
+DELETE_SYNC_TABLES_DB_SCRIPT=<%= @delete_sync_tables_sql %>
+
 
 LOCAL_DB_CREDENTIALS="-u $LOCAL_OPENMRS_DB_USER -p$LOCAL_OPENMRS_DB_PASSWORD"
 
@@ -29,5 +31,15 @@ if [ "$?" = "0" ]; then
 	echo "OpenMRS db has been imported"
 else
 	echo "Failed to import OpenMRS DB" 1>&2
+	exit 1
+fi
+
+# delete sync tables from the local server 
+echo "Delete sync tables"
+$MYSQL_CLIENT $LOCAL_DB_CREDENTIALS $OPENMRS_DB < $DELETE_SYNC_TABLES_DB_SCRIPT
+if [ "$?" = "0" ]; then
+	echo "sync tables have been deleted"
+else
+	echo "Failed to delete sync tables" 1>&2
 	exit 1
 fi
